export const ADD_TO_CART = 'ADD_TO_CART';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const GET_NUMBER_CART = 'GET_NUMBER_CART';
export const GET_CART_ITEM = 'GET_CART_ITEM';
export const CHANGE_NUMBER_ITEM = 'CHANGE_NUMBER_ITEM';
export const DELETE_ITEM_IN_CART = 'DELETE_ITEM_IN_CART';
export const TOTAL_PRICE = 'TOTAL_PRICE';
